### PR TITLE
fixed the image urls

### PR DESCRIPTION
**Pull request by jasondewitt**
implemented the fix from issue #55 by updating the image URLs to point to site_id 2 on wptest.io so that attachment import no longer 404s

### CODE REVIEW

**Comment by JeremyEnglert** [comment]
@Poststatus, this should be merged.

**Comment by metaColin** [comment]
+1 please merge!

**Comment by ricotheque** [comment]
Another +1 for merging this PR.

**Comment by robneu** [comment]
Any reason why this hasn't been merged yet? If you need help maintaining this repo I'm sure lots of people would be willing to do so, myself included.

**Comment by krogsgard** [comment]
This is merged now -- sorry my notifications got messed up for Github. Thanks @jasondewitt for the PR!

**Pull request merged**
